### ISSUE TITLE
Estimated Z position significantly different from vision z

### ISSUE THREAD

**Issue by Seanmatthews** [Pensasystems/Firmware#2]
From @gssammy:

While running an avoidance behaviour, on ascent the vehicle crashed into the light and then the roof and bounced for a while before shutting off. On examination of the ulog file and based on accounts of the incident, the vision position z was more accurate than what the local position z graph showed. This leads to the conclusion the estimator may need to be examined. The setting for LPE_FUSION is currently set to 12 in px4 config files (not sure if this is what we want).

ulog:https://drive.google.com/open?id=1ItNkJt1yXw0bSHXR8oGWSuLMTqlbUd3p
rosbag: https://drive.google.com/open?id=1qk83RySHIrn_EyOHm5Q5EIqPCAbEDnwr
 
---

gssammy commented on Jan 10 • 
After a discussion about how the system works, it was found that the raw imu data and vision data is fed into snapdragon_mavros to create vision pose estimates. These estimates are then fed to the LPE estimator along with raw accelerometer data to create the local position estimates. An estimator running on estimated data and raw data which was already included in the supplied estimator data.

Possible solution plan is to tune px4 side estimator (LPE) to trust the vision measurements more. How to trigger the issue and then test whether the response is better after tunning is still being formulated.

Furthur down the road, it may be good to look at snap_cam to get optical flow data and then have only the LPE do fusing with accelerometer data.

**Comment by gssammy** [comment]
This has not been seen since and may have been fixed by using IMU_SCALED data instead to fed VIO, upgrading PX4, tunning and other enhancements.
